topcoder-platform/taas-app

.circleci/config.yml

- chore: stop deploying mock server

Dry Release v0.1 attempt 2

---

src/hoc/withAuthentication.js

fix: issue #44

---

config/development.js
config/production.js
src/routes/MyTeamsDetails/components/TeamSummary/index.jsx
src/routes/MyTeamsDetails/components/TeamSummary/styles.module.scss
src/routes/MyTeamsDetails/index.jsx
src/routes/MyTeamsList/components/TeamCard/index.jsx
src/utils/format.js

- #51 feat: add link to Connect Project

Dry Release v0.2.1

---

src/constants/index.js
src/constants/permissions.js
src/hoc/withAuthentication/actions/index.js
src/hoc/withAuthentication/index.js
src/hoc/withAuthentication/reducers/index.js
src/routes/JobForm/utils.js
src/routes/MyTeamsDetails/components/TeamMembers/index.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/ResourceBookingDetails/index.jsx
src/routes/ResourceBookingForm/utils.js
src/routes/TeamAccess/actions/index.js
src/utils/permissions.js

https://github.com/topcoder-platform/taas-app/issues/83

Permissions part 2 - permission based on Project Roles (members)

---

config/index.js

Use PROD environment by default.

[PROD] [HOTFIX] Post Release Patch 1.5.1

---

src/routes/MyTeamsList/components/TeamCard/index.jsx

fix: issue #128

---

src/components/FormField/index.jsx
src/components/MarkdownEditor/index.jsx
src/components/MarkdownEditor/styles.module.scss
src/constants/index.js
src/routes/JobForm/index.jsx
src/routes/JobForm/utils.js

fix: issue #125

---

src/components/User/index.jsx
src/components/User/styles.module.scss
src/routes/TeamAccess/components/MemberList/index.jsx
src/routes/TeamAccess/components/MemberList/styles.module.scss

fix: issue #135

---

config/index.js
src/components/FormField/index.jsx
src/components/MarkdownEditor/index.jsx
src/components/MarkdownEditor/styles.module.scss
src/components/ReactSelect/index.jsx
src/routes/JobForm/index.jsx
src/routes/JobForm/utils.js

fix: issue #138

---

config/index.js
src/components/DateInput/styles.module.scss
src/components/MarkdownEditor/index.jsx
src/components/MarkdownEditor/styles.module.scss
src/components/ReactSelect/index.jsx
src/components/TextInput/styles.module.scss
src/components/User/index.jsx
src/components/User/styles.module.scss
src/routes/TeamAccess/components/MemberList/index.jsx
src/routes/TeamAccess/components/MemberList/styles.module.scss
src/services/teams.js
src/styles/main.vendor.scss
webpack.config.js

- none
- feat: Disable Job Edit form when status is "assigned", "cancelled" or "closed" https://github.com/topcoder-platform/taas-app/issues/138
- fix: respect `APPENV` when building for DEV/PROD

[PROD] Patch Release 1.5.3

---

.gitignore
src/constants/index.js

- feat: add JC status "topcoder-rejected" https://github.com/topcoder-platform/taas-app/issues/142

[PROD] Patch 1.5.3.1

---

src/routes/ResourceBookingForm/index.jsx

https://github.com/topcoder-platform/taas-app/issues/150

feat: don't use time for Resource Bookings

---

src/constants/index.js
src/routes/JobForm/index.jsx
src/routes/PositionDetails/actions/index.js
src/routes/PositionDetails/components/InterviewConfirmPopup/index.jsx
src/routes/PositionDetails/components/InterviewDetailsPopup/index.jsx
src/routes/PositionDetails/components/InterviewDetailsPopup/styles.module.scss
src/routes/PositionDetails/components/LatestInterview/index.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/PositionDetails/components/PreviousInterviewsPopup/index.jsx
src/services/teams.js
src/utils/helpers.js

1. Remove mocked parts & integrate with the API.

feat(interview-scheduler): backend integration

---

src/components/ActionsMenu/index.jsx
src/components/ActionsMenu/styles.module.scss
src/constants/index.js
src/routes/PositionDetails/components/InterviewDetailsPopup/index.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/PositionDetails/components/SelectCandidatePopup/index.jsx
src/routes/PositionDetails/components/SelectCandidatePopup/styles.module.scss
src/routes/PositionDetails/reducers/index.js

Addresses:
https://github.com/topcoder-platform/taas-app/issues/158
https://github.com/topcoder-platform/taas-app/issues/159
https://github.com/topcoder-platform/taas-app/issues/161
https://github.com/topcoder-platform/taas-app/issues/163
https://github.com/topcoder-platform/taas-app/issues/164
https://github.com/topcoder-platform/taas-app/issues/165
https://github.com/topcoder-platform/taas-app/issues/170
https://github.com/topcoder-platform/taas-app/issues/171
https://github.com/topcoder-platform/taas-app/issues/173

fix(interview-scheduler): various fixes & improvements

---

src/routes/JobForm/index.jsx

Addresses https://github.com/topcoder-platform/taas-app/issues/179

fix(interview-scheduler): remove externalId assignment to userId

---

src/routes/PositionDetails/components/InterviewConfirmPopup/index.jsx

As per https://github.com/topcoder-platform/taas-app/issues/180

Remove embedded video

---

src/routes/PositionDetails/components/InterviewConfirmPopup/index.jsx
src/routes/PositionDetails/components/InterviewDetailsPopup/index.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/PositionDetails/components/PrevInterviewItem/index.jsx

Fixing a few content bugs

---

src/components/TCForm/utils.js
src/routes/JobForm/index.jsx
src/routes/ResourceBookingForm/index.jsx
src/services/jobs.js
src/services/resourceBookings.js

fix: use PATCH instead of PUT for Job and RB saving

---

src/root.component.jsx
src/routes/CreateNewTeam/components/Completeness/index.jsx
src/routes/CreateNewTeam/components/Completeness/styles.module.scss
src/routes/CreateNewTeam/index.jsx
src/routes/CreateNewTeam/pages/InputJobDescription/components/SkillListPopup/index.jsx
src/routes/CreateNewTeam/pages/InputJobDescription/components/SkillListPopup/styles.module.scss
src/routes/CreateNewTeam/pages/InputJobDescription/index.jsx
src/routes/CreateNewTeam/pages/InputJobDescription/styles.module.scss
src/services/teams.js

@nikolay83 please close #289  and review this one

Role & Skills Intake - Job Description Module

---

src/services/roles.js

* Remove mock data.
* Integrate backend endpoints to retrieve role(s) data.

feat(role-intake): integrate roles endpoint to retrieve roles

---

src/assets/images/icon-role-fallback-old.svg
src/assets/images/icon-role-fallback.svg
src/routes/CreateNewTeam/actions/index.js
src/routes/CreateNewTeam/components/NoMatchingProfilesResultCard/index.jsx
src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx
src/routes/CreateNewTeam/components/SearchContainer/index.jsx
src/routes/CreateNewTeam/components/SubmitContainer/index.jsx
src/routes/CreateNewTeam/components/SuccessCard/index.jsx
src/routes/CreateNewTeam/index.jsx
src/routes/CreateNewTeam/pages/InputSkills/components/SkillItem/index.jsx
src/routes/CreateNewTeam/pages/SelectRole/index.jsx
src/routes/CreateNewTeam/reducers/index.js

Role quick fixes - navigation to landing and keeping roles selected in localStorage until they are submitted

Role quick fixes

---

src/routes/CreateNewTeam/components/NoMatchingProfilesResultCard/index.jsx
src/routes/CreateNewTeam/components/SearchContainer/index.jsx

Fix for: [https://github.com/topcoder-platform/taas-app/issues/340](https://github.com/topcoder-platform/taas-app/issues/340)

Fixed crash when empty object returned from /sendRoleSearchRequest

---

src/routes/CreateNewTeam/components/InputContainer/index.jsx

fix: show jd popup

---

src/routes/CreateNewTeam/components/TeamDetailsModal/index.jsx
src/routes/CreateNewTeam/components/TeamDetailsModal/utils/validator.js

fix: validate resources and duration fields when both deleted.

---

src/routes/CreateNewTeam/components/EditRoleForm/index.jsx
src/routes/CreateNewTeam/components/EditRoleForm/styles.module.scss
src/routes/CreateNewTeam/components/EditRoleForm/utils/validator.js
src/routes/CreateNewTeam/components/ResultCard/index.jsx
src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx
src/routes/CreateNewTeam/components/SearchContainer/index.jsx

Issue #356

---

src/routes/CreateNewTeam/components/Progress/index.jsx
src/routes/CreateNewTeam/components/Progress/styles.module.scss

fix: issue #375 deploy error

---

src/routes/CreateNewTeam/styles.module.scss

fix: issue #355

---

src/constants/index.js

This PR fixes: https://github.com/topcoder-platform/taas-app/issues/393

add withdrawn status candidate in decline tab

---

src/components/CustomerScroll/styles.module.scss
src/constants/index.js
src/root.component.jsx
src/routes/CreateNewTeam/styles.module.scss
src/routes/PositionDetails/index.jsx

feat: Support direct links to the Job Candidates tabs.

---

src/routes/JobForm/utils.js
src/routes/PositionDetails/index.jsx

fix: Enable save button if duration field is null & Update URL on Job Candidate tab change

---

src/routes/CreateNewTeam/components/ResultCard/index.jsx
src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx
src/routes/CreateNewTeam/components/SearchContainer/index.jsx
src/routes/CreateNewTeam/components/SkillTag/index.jsx
src/routes/CreateNewTeam/components/SkillTag/styles.module.scss
src/routes/CreateNewTeam/components/SubmitContainer/index.jsx
src/routes/CreateNewTeam/pages/SelectRole/components/RoleStaticCard/index.jsx
src/routes/CreateNewTeam/pages/SelectRole/components/RoleStaticCard/styles.module.scss
src/routes/CreateNewTeam/pages/SelectRole/components/RolesList/index.jsx

fix: issue #416 #412

---

src/routes/CreateNewTeam/components/LandingBox/index.jsx
src/routes/CreateNewTeam/components/LandingBox/styles.module.scss
src/routes/CreateNewTeam/pages/CreateTeamLanding/index.jsx
src/routes/CreateNewTeam/pages/CreateTeamLanding/styles.module.scss

fix: issue #411

---

src/routes/CreateNewTeam/components/ResultCard/index.jsx
src/routes/CreateNewTeam/components/ResultCard/styles.module.scss
src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx

fix: issue #412

---

src/root.component.jsx

fix: issue #460

---

src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx
src/routes/CreateNewTeam/pages/CreateTaasPayment/PaymentForm/index.jsx
src/routes/CreateNewTeam/pages/CreateTaasPayment/PaymentResultPopup/index.jsx
src/routes/CreateNewTeam/pages/CreateTaasPayment/PaymentResultPopup/styles.module.scss

fix: issue #461 #464

---

src/routes/CreateNewTeam/pages/CreateTaasPayment/styles.module.scss

Addresses https://github.com/topcoder-platform/taas-app/issues/440

fix(create-new-team): add padding to payment container

---

src/routes/CreateNewTeam/components/EditRoleForm/index.jsx
src/routes/CreateNewTeam/components/SubmitContainer/index.jsx

* (99d5b57) fix(create-new-team): initialValue of MonthPicker on EditRoleForm
Addresses #415
* (426b2c9) fix(create-new-team): increase delay before redirection
Addresses #361 (comment)

Fix MonthPicker on EditRoleForm & Increase Delay Before Redirection

---

src/services/roles.js

fix: issue #462

---

src/routes/CreateNewTeam/components/ResultCard/index.jsx
src/routes/CreateNewTeam/pages/InputJobDescription/index.jsx

fix: Show job title in No Results page

---

src/routes/CreateNewTeam/components/SubmitContainer/index.jsx

Addresses https://github.com/topcoder-platform/taas-app/issues/486

feat(create-new-team): post `intakeSource` in `createTeam` req.

---

src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx
src/routes/CreateNewTeam/pages/InputJobDescription/index.jsx
src/routes/CreateNewTeam/pages/InputSkills/index.jsx
src/routes/CreateNewTeam/pages/SelectRole/index.jsx

fix: issue #482, #483

---

src/root.component.jsx
src/routes/CreateNewTeam/components/SearchAndSubmit/index.jsx

[PROD] Next Release

---

src/root.component.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/PositionDetails/components/PositionCandidates/styles.module.scss
src/services/requestInterceptor.js
src/services/teams.js

- Support Download Resume notification

[PROD] Next Release Patch

---

src/routes/JobForm/index.jsx
src/services/teams.js
src/utils/format.js

fix issue topcoder-platform/taas-apis#507

---

src/components/Select/styles.module.scss

fix: issue #543

---

src/components/Accordion/index.jsx
src/components/Accordion/styles.module.scss
src/routes/PositionDetails/components/PrevInterviewItem/index.jsx
src/routes/PositionDetails/components/PreviousInterviewsPopup/index.jsx

fix: issue #256

---

src/components/NylasSchedulerPage/index.jsx
src/root.component.jsx
src/routes/CancelInterviewPage/index.jsx
src/routes/PositionDetails/components/InterviewPopup/Confirm/index.jsx
src/routes/RescheduleInterviewPage/index.jsx
src/routes/SchedulingPage/index.jsx

Changes for issue https://github.com/topcoder-platform/taas-apis/issues/587.

Added interview cancel & reschedule page.

---

src/routes/CancelInterviewPage/index.jsx
src/routes/CancelInterviewPage/styles.module.scss
src/services/interviews.js
src/services/teams.js

fix: issue #575

---

src/server/misc/routes/index.html
src/server/misc/routes/interview-thank-you-page.js

fix: issue #562

---

src/routes/CancelInterviewPage/index.jsx
src/services/teams.js

fix: issue #583

---

src/routes/PositionDetails/components/CandidatesStatusFilter/index.jsx
src/routes/PositionDetails/components/PositionCandidates/index.jsx
src/routes/PositionDetails/index.jsx

fix: issue #586

---

src/constants/index.js
src/routes/PositionDetails/components/InterviewPopup/CalendarSyncTimedOut/index.jsx
src/routes/PositionDetails/components/InterviewPopup/CalendarSyncTimedOut/styles.module.scss
src/routes/PositionDetails/components/InterviewPopup/Confirm/index.jsx
src/routes/PositionDetails/components/InterviewPopup/Confirm/styles.module.scss
src/routes/PositionDetails/components/InterviewPopup/index.jsx
src/routes/PositionDetails/components/InterviewPopup/styles.module.scss
src/server/misc/routes/interview-thank-you-page.js
src/utils/helpers.js

This commit addresses issue https://github.com/topcoder-platform/taas-app/issues/588.

Implemented functionality to wait & sync host's calendar before requesting interview.

---

src/routes/PositionDetails/components/InterviewPopup/ManageAvailability/styles.module.scss
src/routes/PositionDetails/components/InterviewPopup/SelectDuration/styles.module.scss

fix: issue #585

---

src/routes/PositionDetails/components/InterviewPopup/ManageAvailability/index.jsx
src/routes/PositionDetails/components/InterviewPopup/SelectDuration/index.jsx

#598 [DEV] Hide connect calendar feature

---

src/constants/index.js
src/routes/PositionDetails/components/InterviewPopup/ManageAvailability/index.jsx
src/routes/PositionDetails/components/InterviewPopup/ScheduleInterview/index.jsx
src/routes/PositionDetails/components/InterviewPopup/ScheduleInterview/styles.module.scss
src/routes/PositionDetails/components/InterviewPopup/SelectDuration/index.jsx

fix: issue #598
